# Generated by Django 6.0.6 on 2026-06-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default', null=True)),
                ('content', models.TextField(default='default', null=True)),
                ('price', models.IntegerField(default=1000)),
            ],
        ),
    ]
